[versions]
agp = "8.3.1"
kotlin = "1.9.23"
ksp = "1.9.0-1.0.12"
core-ktx = "1.12.0"
appcompat = "1.6.1"
material = "1.11.0"
compose-bom = "2024.03.00"
nav-version = "2.7.7"
lottie = "6.4.0"
lottie-compose = "4.0.0"

okhttp-bom = "4.12.0"
gson = "2.10.1"
retrofit = "2.9.0"
hilt = "2.51.1"
hilt-navigation-compose = "1.2.0"
lifecycle-runtime-compose = "2.7.0"
coil-compose = "2.6.0"


[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
activity-compose = { group = "androidx.activity", name = "activity-compose" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "nav-version" }
lottie = {group = "com.airbnb.android", name = "lottie", version.ref = "lottie"}
lottie-compose = {group = "com.airbnb.android", name = "lottie-compose", version.ref ="lottie-compose"}

okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp-bom" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = {group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose"}
lifecycle-runtime-compose = {group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose"}
coil-compose = {group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
hilt = {id = "com.google.dagger.hilt.android", version.ref = "hilt"}

