name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Instrumental tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        target: google_apis
        api-level: 34
        arch: arm64-v8a
        script: ./gradlew connectedCheck
    - name: Archive APK artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Send APK to Telegram
      env:
        APK_PATH: app/build/outputs/apk/debug/app-debug.apk
        BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        curl -F document=@"${APK_PATH}" https://api.telegram.org/bot${BOT_API_KEY}/sendDocument?chat_id=${CHAT_ID}
        

