name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
  ktlint:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
    - name: Ktlint
      run: ./gradlew ktlintCheck

  detekt:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
    - name: Detekt
      run: ./gradlew detekt
    
  
  
